---
# tasks file for mysql_DBrole
    - name: Install MySQL database
      apt:
        name: "{{ item }}"
        state:  present
      with_items:
       - mysql-server
       - mysql-client
    - name: Start Mysql Service
      service:
        name: mysql
        state: started
        enabled: yes
    - name: Create Application Database
      mysql_db: 
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ db_name }}" 
        state: present
    - name: Create Application DB User
      mysql_user: 
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ db_user }}" 
        password: "{{ db_password }}" 
        priv: '*.*:ALL' 
        host: '%' 
        state: 'present'